### ISSUE TITLE
I noticed a little gap on the right in thumbnails

### ISSUE THREAD

**Issue by sunlitweb** [ksylvest/jquery-carousel#1]
I haven't uploaded my webpage to a server yet. I'm still designing it in Dreamweaver.

The thumbnails in your carousel have about a three pixel gap on the right. That row isn't quite wide enough to cover the width of the slides below. 

Here is my code. First is my css, then my html. And of course I am using your main.css file with it. That is below my code. I am also using your images to test my design.

Thank you. You have everything you need to investigate it now. 

@charset "utf-8";
/\* CSS Document */

/\* *******************************************************************\* _/ 
/_                  Generated by: http://csscreator.com                 _/
/_ *******************************************************************\* */
html, body{
    margin:0;
    padding:0;
    text-align:center;
    color: #000000;
} 
# pagewidth{

```
width:960px;
text-align:center;
margin:0 auto;
```

} 
# header{

```
position:relative;
height:565px;
background-color:#FFFAD6;
width:936px;
display:block;
overflow:auto;
padding: 12px;
```

} 
# leftcol{

```
width:196px;
float:left;
position:relative;
background-color:#FF9B94;
padding: 12px;
height: 800px;
```

 }
# maincol{

```
background-color: #E5DAC4;
position: relative;
width:716px;
float:right;
padding: 12px;
height: 800px;
```

 }
# footer{

```
height:100px;
background-color:#649193;
clear:both;
display:block;
overflow:auto;
padding: 12px;
```

} 

p {color="5E5E5E";}

/\* *******************************************************************\* _/ 
/_ Clearfix: http://csscreator.com/attributes/containedfloat.php        _/
/_ *******************************************************************\* */
.clearfix:after {
 content: "."; 
 display: block; 
height: 0; 
 clear: both; 
 visibility: hidden;
 }

.clearfix{display: inline-block;}

/\* Hides from IE-mac */
- html .clearfix{height: 1%;}
  .clearfix{display: block;}
  /\* End hide from IE-mac */  

/\* *******************************************************************\* _/ 
/_                      printer styles                                  _/ 
/_ *******************************************************************\* */ 

 @media print{ 
/_hide the left column when printing_/ 
# leftcol{display:none;}
# twocols, #maincol{width:100%; float:none;}

}

---

<!doctype html>
<html>
<head>
<title>CssCreator-->HTML5 Template</title>
<meta charset="utf-8" />
<meta generator="csscreator.com" />

<link rel="stylesheet" href="css/main.css" type="text/css" />
<link rel="stylesheet" href="styles.css" type="text/css" />

</head>
<body>

<div id="pagewidth" >
    <div id="header">
    <div class="container">

    
      <div class="carouselThis" id="carousel">       
         
         <div id="carouselThis-frame">
            
            <ol>
               <li>
                  <img src="img/slides/slide1.png" alt="" />
               </li>
               <li>
                     <img src="img/slides/slide2.png" alt="" />
               </li>
               <li>
                     <img src="img/slides/slide3.png" alt="" />
               </li>
               <li>
                  <img src="img/slides/slide4.png" alt="" />
               </li>
               <li>
                     <img src="img/slides/slide5.png" alt="" />
               </li>
               <li>
                     <img src="img/slides/slide6.png" alt="" />
               </li>
               <li>
                     <img src="img/slides/slide7.png" alt="" />
               </li>

            </ol>
            
         </div>

```
     <a href="" id="leftBtn">LEFT</a>
     <a href="" id="rightBtn">RIGHT</a>
  </div>
</div>
```

   </div>

```
<div id="wrapper" class="clearfix">
        <div id="maincol"><h1>Main Content Column</h1></div>
    <div id="leftcol"> <h2>Left Column</h2></div>
</div>
<footer id="footer"><h2>Footer</h2></footer>
</div>
```

<script src="js/jquery-1.8.js"></script>

<script src="js/jquery-easing.js"></script>

<script src="js/carouselthis.jquery.js"></script>

<script>
$(function(){ 
   $('#carousel').carouselThis({
      'easingMethod' : 'easeOutQuint',
      'navigation' : {
         'type' : 'thumbnail',
         'leftBtnId' : 'leftBtn',
         'rightBtnId' : 'rightBtn'
      }
   });
})
</script>

</body>
</html>

---

/\* Eric Meyer's Reset CSS v2.0 */
html,body,div,span,applet,object,iframe,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{border:0;font-size:100%;font:inherit;vertical-align:baseline;margin:0;padding:0}article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}body{line-height:1}ol,ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:none}table{border-collapse:collapse;border-spacing:0}

/\* =============================================================================
   General Styles
   ========================================================================== */

html {font-size:16px; /\* Rest font size */}

body { font-family: Arial; font-size: 62.5%; /\* 1em = 10px */}

p { line-height: 1.2em }

h1 { font-size: 3em }

.container {
    margin: 0 auto;
    width: 880px;
    height: 100%;
    background-color:#FFFAD6
}

/\* =============================================================================
   Base
   ========================================================================== */

.carouselThis-wrapper {

```
float: left;
clear: left;
```

}

.carouselThis-wrapper > ol > li {
    float: left;
}
# carouselThis-frame { overflow: hidden;clear: left}

/\* =============================================================================
   nav
   ========================================================================== */

 .carouselThis-menu {
    float: left;
 }

 .carouselThis-menu > li {
    display: inline;
 }

.carouselThis-menu > li img {
    width: 10em;
 }
# leftBtn {

```
font-weight: bold;
font-size: 2em;
float: left;
```

}
# rightBtn {

   font-weight: bold;
   font-size: 2em;
   float:right
}

**Comment by ksylvest** [comment]
It looks like you are using a different carousel library (not this one). Can you please provide a screenshot and reopen if this isn't the case. Thanks.
