### ISSUE TITLE
It is not working in IE why?

### ISSUE THREAD

**Issue by ViktorMoravec** [ksylvest/jquery-carousel#2]

**Comment by ksylvest** [comment]
@ViktorMoravec Please provide more details. Which version of IE? What is happening?

**Comment by ksylvest** [comment]
@ViktorMoravec Closing after no reproduction steps. Please feel free to open with more details.

**Comment by jakeauyeung** [comment]
ie : open page the loading loop

**Comment by ksylvest** [comment]
@jakeauyeung Again I need reproduction steps or a code fix. I opened up the page in IE 10 and it loaded correctly. What version of IE are you using and which page?
